export const paises = [
    {sigla: "AF", nome:"Afeganistão", nomeIngles: "AFGHANISTAN"},
    {sigla: "ZA", nome:"África do Sul", nomeIngles: "SOUTH AFRICA"},
    {sigla: "AL", nome:"Albânia", nomeIngles: "ALBANIA"},
    {sigla: "DE", nome:"Alemanha", nomeIngles: "GERMANY"},
    {sigla: "AD", nome:"Andorra", nomeIngles: "ANDORRA"},
    {sigla: "AQ", nome:"Antárctida", nomeIngles: "ANTARCTICA"},
    {sigla: "BH", nome:"Bahrein", nomeIngles: "BAHRAIN"},
    {sigla: "BQ", nome:"Bonaire", nomeIngles: "BONAIRE, SINT EUSTATIUS AND SABA"},
    {sigla: "BA", nome:"Bósnia e Herzegovina", nomeIngles: "BOSNIA AND HERZEGOVINA"},
    {sigla: "CC", nome:"Ilhas dos Cocos", nomeIngles: "Cocos (Keeling) Islands"},
    {sigla: "CW", nome:"Curaçao", nomeIngles: "Curaçao"},
    {sigla: "TF", nome:"Terras Austrais e Antárticas Francesas", nomeIngles: "French Southern Territories"},
    {sigla: "GG", nome:"Guernsey", nomeIngles: "Guernsey"},
    {sigla: "GW", nome:"Guiné-Bissau", nomeIngles: "GUINEA-BISSAU"},
    {sigla: "JE", nome:"Jersey", nomeIngles: "JERSEY"},
    {sigla: "LA", nome:"Laos", nomeIngles: "Lao People's Democratic Republic"},
    {sigla: "LY", nome:"Líbia", nomeIngles: "LIBYA"},
    {sigla: "IM", nome:"Ilha de Man", nomeIngles: "Isle of Man"},
    {sigla: "IR", nome:"Irão", nomeIngles: "Iran (Islamic Republic of)"},
    {sigla: "VA", nome:"Vaticano", nomeIngles: "Vatican City"},
    {sigla: "HM", nome:"Ilha Heard e Ilhas McDonald", nomeIngles: "Heard Island and McDonald Islands"},
    {sigla: "GM", nome:"Gâmbia", nomeIngles: "GAMBIA"},
    {sigla: "FJ", nome:"Fiji", nomeIngles: "FIJI"},
    {sigla: "CD", nome:"RD Congo", nomeIngles: "CONGO (Democratic Republic of the)"},
    {sigla: "KM", nome:"Comores", nomeIngles: "COMOROS"},
    {sigla: "AO", nome:"Angola", nomeIngles: "ANGOLA"},
    {sigla: "AI", nome:"Anguila", nomeIngles: "ANGUILLA"},
    {sigla: "AG", nome:"Antígua e Barbuda", nomeIngles: "ANTIGUA AND BARBUDA"},
    {sigla: "AN", nome:"Antilhas Holandesas", nomeIngles: "NETHERLANDS ANTILLES"},
    {sigla: "SA", nome:"Arábia Saudita", nomeIngles: "SAUDI ARABIA"},
    {sigla: "DZ", nome:"Argélia", nomeIngles: "ALGERIA"},
    {sigla: "AR", nome:"Argentina", nomeIngles: "ARGENTINA"},
    {sigla: "AM", nome:"Armênia", nomeIngles: "ARMENIA"},
    {sigla: "AW", nome:"Aruba", nomeIngles: "ARUBA"},
    {sigla: "AU", nome:"Austrália", nomeIngles: "AUSTRALIA"},
    {sigla: "AT", nome:"Áustria", nomeIngles: "AUSTRIA"},
    {sigla: "AZ", nome:"Azerbaijão", nomeIngles: "AZERBAIJAN"},
    {sigla: "BS", nome:"Bahamas", nomeIngles: "BAHAMAS"},
    {sigla: "BD", nome:"Bangladesh", nomeIngles: "BANGLADESH"},
    {sigla: "BB", nome:"Barbados", nomeIngles: "BARBADOS"},
    {sigla: "BH", nome:"Barein", nomeIngles: "BAHREIN"},
    {sigla: "BE", nome:"Bélgica", nomeIngles: "BELGIUM"},
    {sigla: "BZ", nome:"Belize", nomeIngles: "BELIZE"},
    {sigla: "BJ", nome:"Benin", nomeIngles: "BENIN"},
    {sigla: "BM", nome:"Bermuda", nomeIngles: "BERMUDA"},
    {sigla: "BY", nome:"Bielorrússia", nomeIngles: "BELARUS"},
    {sigla: "BO", nome:"Bolívia", nomeIngles: "BOLIVIA (PLURINATIONAL STATE OF)"},
    {sigla: "BA", nome:"Bósnia Herzegovina", nomeIngles: "BOSNIA HERZEGOVINA"},
    {sigla: "BW", nome:"Botsuana", nomeIngles: "BOTSWANA"},
    {sigla: "BR", nome:"Brasil", nomeIngles: "BRAZIL"},
    {sigla: "BN", nome:"Brunei", nomeIngles: "BRUNEI DARUSSALAM"},
    {sigla: "BG", nome:"Bulgária", nomeIngles: "BULGARIA"},
    {sigla: "BF", nome:"Burkina Fasso", nomeIngles: "BURKINA FASO"},
    {sigla: "BI", nome:"Burundi", nomeIngles: "BURUNDI"},
    {sigla: "BT", nome:"Butão", nomeIngles: "BHUTAN"},
    {sigla: "CV", nome:"Cabo Verde", nomeIngles: "CABO VERDE"},
    {sigla: "CM", nome:"Camarões", nomeIngles: "CAMEROON"},
    {sigla: "KH", nome:"Camboja", nomeIngles: "CAMBODIA"},
    {sigla: "CA", nome:"Canadá", nomeIngles: "CANADA"},
    {sigla: "QA", nome:"Catar", nomeIngles: "QATAR"},
    {sigla: "KZ", nome:"Cazaquistão", nomeIngles: "KAZAKHSTAN"},
    {sigla: "TD", nome:"Chade", nomeIngles: "CHAD"},
    {sigla: "CL", nome:"Chile", nomeIngles: "CHILE"},
    {sigla: "CN", nome:"China", nomeIngles: "CHINA"},
    {sigla: "CY", nome:"Chipre", nomeIngles: "CYPRUS"},
    {sigla: "CO", nome:"Colômbia", nomeIngles: "COLOMBIA"},
    {sigla: "CG", nome:"Congo", nomeIngles: "CONGO"},
    {sigla: "KP", nome:"Coréia do Norte", nomeIngles: "KOREA – DEM. PEOPLE’S RE"},
    {sigla: "KR", nome:"Coréia do Sul", nomeIngles: "KOREA – REP. OF"},
    {sigla: "CI", nome:"Costa do Marfim", nomeIngles: "COTE D’IVOIRE"},
    {sigla: "CR", nome:"Costa Rica", nomeIngles: "COSTA RICA"},
    {sigla: "HR", nome:"Croácia", nomeIngles: "CROATIA"},
    {sigla: "CU", nome:"Cuba", nomeIngles: "CUBA"},
    {sigla: "DK", nome:"Dinamarca", nomeIngles: "DENMARK"},
    {sigla: "DJ", nome:"Djibuti", nomeIngles: "DJIBOUTI"},
    {sigla: "DM", nome:"Dominica", nomeIngles: "DOMINICA"},
    {sigla: "EG", nome:"Egito", nomeIngles: "EGYPT"},
    {sigla: "SV", nome:"El Salvador", nomeIngles: "EL SALVADOR"},
    {sigla: "AE", nome:"Emirados Árabes Unidos", nomeIngles: "UNITED ARAB EMIRATES"},
    {sigla: "EC", nome:"Equador", nomeIngles: "ECUADOR"},
    {sigla: "ER", nome:"Eritréia", nomeIngles: "ERITREA"},
    {sigla: "SK", nome:"Eslováquia", nomeIngles: "SLOVAK REPUBLIC"},
    {sigla: "SI", nome:"Eslovênia", nomeIngles: "SLOVENIA"},
    {sigla: "ES", nome:"Espanha", nomeIngles: "SPAIN"},
    {sigla: "US", nome:"Estados Unidos", nomeIngles: "UNITED STATES"},
    {sigla: "EE", nome:"Estônia", nomeIngles: "ESTONIA"},
    {sigla: "ET", nome:"Etiópia", nomeIngles: "ETHIOPIA"},
    {sigla: "PH", nome:"Filipinas", nomeIngles: "PHILIPPINES"},
    {sigla: "FI", nome:"Finlândia", nomeIngles: "FINLAND"},
    {sigla: "FR", nome:"França", nomeIngles: "FRANCE"},
    {sigla: "GA", nome:"Gabão", nomeIngles: "GABON"},
    {sigla: "GH", nome:"Gana", nomeIngles: "GHANA"},
    {sigla: "GI", nome:"Gibraltar", nomeIngles: "GIBRALTAR"},
    {sigla: "GD", nome:"Granada", nomeIngles: "GRENADA"},
    {sigla: "GR", nome:"Grécia", nomeIngles: "GREECE"},
    {sigla: "GL", nome:"Groenlândia", nomeIngles: "GREENLAND"},
    {sigla: "GP", nome:"Guadalupe", nomeIngles: "GUADELOUPE"},
    {sigla: "GU", nome:"Guam", nomeIngles: "GUAM"},
    {sigla: "GT", nome:"Guatemala", nomeIngles: "GUATEMALA"},
    {sigla: "GY", nome:"Guiana", nomeIngles: "GUYANA"},
    {sigla: "GF", nome:"Guiana Francesa", nomeIngles: "FRENCH GUIANA"},
    {sigla: "GN", nome:"Guiné", nomeIngles: "GUINEA"},
    {sigla: "GQ", nome:"Guiné Equatorial", nomeIngles: "EQUATORIAL GUINEA"},
    {sigla: "HT", nome:"Haiti", nomeIngles: "HAITI"},
    {sigla: "NL", nome:"Holanda", nomeIngles: "NETHERLANDS"},
    {sigla: "HN", nome:"Honduras", nomeIngles: "HONDURAS"},
    {sigla: "HK", nome:"Hong Kong", nomeIngles: "HONG KONG"},
    {sigla: "HU", nome:"Hungria", nomeIngles: "HUNGARY"},
    {sigla: "YE", nome:"Iêmen", nomeIngles: "YEMEN ARAB REP."},
    {sigla: "BV", nome:"Ilha Bouvet", nomeIngles: "BOUVET ISLAND"},
    {sigla: "UM", nome:"Ilha Minor Outlying", nomeIngles: "U.S. MINOR OUTLYING ISLA"},
    {sigla: "NF", nome:"Ilha Norfolk", nomeIngles: "NORFOLK ISLAND"},
    {sigla: "RE", nome:"Ilha Reunião", nomeIngles: "REUNION ISLAND"},
    {sigla: "ST", nome:"Ilha São Tomé e Príncipe", nomeIngles: "SÃO TOMÉ AND PRÍNCIPE"},
    {sigla: "KY", nome:"Ilhas Cayman", nomeIngles: "CAYMAN ISLANDS"},
    {sigla: "CX", nome:"Ilhas Christmas", nomeIngles: "CHRISTMAS ISLAND"},
    {sigla: "CC", nome:"Ilhas Coco", nomeIngles: "COCOS ISLANDS"},
    {sigla: "KM", nome:"Ilhas Comoro", nomeIngles: "COMORO ISLANDS"},
    {sigla: "CK", nome:"Ilhas Cook", nomeIngles: "COOK ISLANDS"},
    {sigla: "FK", nome:"Ilhas Falkland", nomeIngles: "FALKLAND ISLANDS"},
    {sigla: "FO", nome:"Ilhas Faroe", nomeIngles: "FAROE ISLANDS"},
    {sigla: "HM", nome:"Ilhas Heard & McDonald", nomeIngles: "HEARD AND MCDONALD ISLAN"},
    {sigla: "MP", nome:"Ilhas Mariana do Norte", nomeIngles: "NORTHERN MARIANA ISLANDS"},
    {sigla: "MH", nome:"Ilhas Marshall", nomeIngles: "MARSHALL ISLANDS"},
    {sigla: "MU", nome:"Ilhas Maurício", nomeIngles: "MAURITIUS"},
    {sigla: "SB", nome:"Ilhas Salomão", nomeIngles: "SOLOMON ISLANDS"},
    {sigla: "SJ", nome:"Ilhas Svalbard & Jan Mayan", nomeIngles: "SVALBARD & JAN MAYAN ISL"},
    {sigla: "TC", nome:"Ilhas Turks e Caicos", nomeIngles: "TURKS AND CAICOS ISLANDS"},
    {sigla: "VI", nome:"Ilhas Virgens Americanas", nomeIngles: "U.S.VIRGIN ISLANDS"},
    {sigla: "VG", nome:"Ilhas Virgens Britânicas", nomeIngles: "BRITISH VIRGIN ISLANDS"},
    {sigla: "WF", nome:"Ilhas Wallis e Futuna", nomeIngles: "WALLIS AND FUTUNA ISLAND"},
    {sigla: "IN", nome:"Índia", nomeIngles: "INDIA"},
    {sigla: "ID", nome:"Indonésia", nomeIngles: "INDONESIA"},
    {sigla: "IG", nome:"Inglaterra", nomeIngles: "ENGLAND"},
    {sigla: "IR", nome:"Irã", nomeIngles: "IRAN"},
    {sigla: "IQ", nome:"Iraque", nomeIngles: "IRAQ"},
    {sigla: "IE", nome:"Irlanda", nomeIngles: "IRELAND"},
    {sigla: "IS", nome:"Islândia", nomeIngles: "ICELAND"},
    {sigla: "IL", nome:"Israel", nomeIngles: "ISRAEL"},
    {sigla: "IT", nome:"Itália", nomeIngles: "ITALY"},
    {sigla: "YU", nome:"Iugoslavia", nomeIngles: "YUGOSLAVIA"},
    {sigla: "JM", nome:"Jamaica", nomeIngles: "JAMAICA"},
    {sigla: "JP", nome:"Japão", nomeIngles: "JAPAN"},
    {sigla: "JO", nome:"Jordânia", nomeIngles: "JORDAN"},
    {sigla: "KI", nome:"Kiribati", nomeIngles: "KIRIBATI"},
    {sigla: "KW", nome:"Kuweit", nomeIngles: "KUWAIT"},
    {sigla: "LS", nome:"Lesoto", nomeIngles: "LESOTHO"},
    {sigla: "LV", nome:"Letônia", nomeIngles: "LATVIA"},
    {sigla: "LB", nome:"Líbano", nomeIngles: "LEBANON"},
    {sigla: "LR", nome:"Liberia", nomeIngles: "LIBERIA"},
    {sigla: "LY", nome:"Libia", nomeIngles: "LIBYA ARAB JAMAHIRIYA"},
    {sigla: "LI", nome:"Liechtenstein", nomeIngles: "LIECHTENSTEIN"},
    {sigla: "LT", nome:"Lituânia", nomeIngles: "LITHUANIA"},
    {sigla: "LU", nome:"Luxemburgo", nomeIngles: "LUXEMBOURG"},
    {sigla: "MK", nome:"Macedônia", nomeIngles: "MACEDONIA"},
    {sigla: "MG", nome:"Madagascar", nomeIngles: "MALAGASY REPUBLIC"},
    {sigla: "MY", nome:"Malásia", nomeIngles: "MALAYSIA"},
    {sigla: "MW", nome:"Malauí", nomeIngles: "MALAWI"},
    {sigla: "MV", nome:"Maldivas", nomeIngles: "MALDIVES"},
    {sigla: "ML", nome:"Mali", nomeIngles: "MALI"},
    {sigla: "MT", nome:"Malta", nomeIngles: "MALTA"},
    {sigla: "MA", nome:"Marrocos", nomeIngles: "MOROCCO"},
    {sigla: "MQ", nome:"Martinica", nomeIngles: "MARTINIQUE"},
    {sigla: "IM", nome:"Maurícia", nomeIngles: "MAURICIA"},
    {sigla: "MR", nome:"Mauritânia", nomeIngles: "MAURITANIA"},
    {sigla: "YT", nome:"Mayotte", nomeIngles: "MAYOTTE"},
    {sigla: "MX", nome:"México", nomeIngles: "MEXICO"},
    {sigla: "MM", nome:"Mianmar", nomeIngles: "MYANMAR"},
    {sigla: "FM", nome:"Micronésia", nomeIngles: "MICRONESIA"},
    {sigla: "MZ", nome:"Moçambique", nomeIngles: "MOZAMBIQUE"},
    {sigla: "MD", nome:"Moldávia", nomeIngles: "MOLDOVA"},
    {sigla: "MC", nome:"Mônaco", nomeIngles: "MONACO"},
    {sigla: "MN", nome:"Mongólia", nomeIngles: "MONGOLIA"},
    {sigla: "ME", nome:"Montenegro", nomeIngles: "MONTENEGRO"},
    {sigla: "MS", nome:"Montserrat", nomeIngles: "MONTSERRAT"},
    {sigla: "NA", nome:"Namíbia", nomeIngles: "NAMIBIA"},
    {sigla: "NR", nome:"Nauru", nomeIngles: "NAURU"},
    {sigla: "NP", nome:"Nepal", nomeIngles: "NEPAL"},
    {sigla: "NI", nome:"Nicarágua", nomeIngles: "NICARAGUA"},
    {sigla: "NE", nome:"Níger", nomeIngles: "NIGER"},
    {sigla: "NG", nome:"Nigéria", nomeIngles: "NIGERIA"},
    {sigla: "NU", nome:"Niue", nomeIngles: "NIUE"},
    {sigla: "NO", nome:"Noruega", nomeIngles: "NORWAY"},
    {sigla: "NC", nome:"Nova Caledônia", nomeIngles: "NEW CALEDONIA"},
    {sigla: "NZ", nome:"Nova Zelândia", nomeIngles: "NEW ZEALAND"},
    {sigla: "OM", nome:"Omã", nomeIngles: "OMAN"},
    {sigla: "PW", nome:"Palau", nomeIngles: "PALAU"},
    {sigla: "PS", nome:"Palestina", nomeIngles: "PALESTINA"},
    {sigla: "PA", nome:"Panamá", nomeIngles: "PANAMA CITY"},
    {sigla: "PG", nome:"Papua-Nova Guiné", nomeIngles: "PAPUA NEW GUINEA"},
    {sigla: "PK", nome:"Paquistão", nomeIngles: "PAKISTAN"},
    {sigla: "PY", nome:"Paraguai", nomeIngles: "PARAGUAY"},
    {sigla: "PE", nome:"Peru", nomeIngles: "PERU"},
    {sigla: "PN", nome:"Pitcairn", nomeIngles: "PITCAIRN"},
    {sigla: "PF", nome:"Polinésia Francesa", nomeIngles: "FRENCH POLYNESIA"},
    {sigla: "PL", nome:"Polônia", nomeIngles: "POLAND"},
    {sigla: "PR", nome:"Porto Rico", nomeIngles: "PUERTO RICO"},
    {sigla: "PT", nome:"Portugal", nomeIngles: "PORTUGAL"},
    {sigla: "KE", nome:"Quênia", nomeIngles: "KENYA"},
    {sigla: "KG", nome:"Quirguistã", nomeIngles: "KYRGYZSTAN"},
    {sigla: "GB", nome:"Reino Unido", nomeIngles: "UNITED KINGDOM"},
    {sigla: "CF", nome:"República Centro-Africana", nomeIngles: "CENTRAL AFRICAN REPUBLIC"},
    {sigla: "GE", nome:"República da Geórgia", nomeIngles: "GEORGIA"},
    {sigla: "CD", nome:"República Democrática do Congo", nomeIngles: "CONGO DEMOCRATIC REP."},
    {sigla: "DO", nome:"República Dominicana", nomeIngles: "DOMINICAN REPUBLIC"},
    {sigla: "CZ", nome:"República Tcheca", nomeIngles: "CZECH REPUBLIC"},
    {sigla: "RO", nome:"Romênia", nomeIngles: "ROMANIA"},
    {sigla: "RW", nome:"Ruanda", nomeIngles: "RWANDA"},
    {sigla: "RU", nome:"Rússia", nomeIngles: "RUSSIAN FEDERATION"},
    {sigla: "EH", nome:"Saara Ocidental", nomeIngles: "WESTERN SAHARA"},
    {sigla: "BL", nome:"Saint Barthelemy", nomeIngles: "SAINT BARTHELEMY"},
    {sigla: "PM", nome:"Saint-Pierre e Miquelon", nomeIngles: "SAINT PIERRE AND MIQUELON"},
    {sigla: "AS", nome:"Samoa Americana", nomeIngles: "AMERICAN SAMOA"},
    {sigla: "WS", nome:"Samoa Ocidental", nomeIngles: "WESTERN SAMOA"},
    {sigla: "SM", nome:"San Marino", nomeIngles: "SAN MARINO"},
    {sigla: "SH", nome:"Santa Helena", nomeIngles: "SAINT HELENA"},
    {sigla: "LC", nome:"Santa Lúcia", nomeIngles: "SAINT LUCIA"},
    {sigla: "KN", nome:"São Cristóvão e Névis", nomeIngles: "SAINT KITTS AND NEVIS"},
    {sigla: "TS", nome:"São Martinho", nomeIngles: "SAINT MARTIN"},
    {sigla: "VC", nome:"São Vicente e Granadinas", nomeIngles: "SAINT VINCENT AND THE GRENADINES"},
    {sigla: "YC", nome:"Seicheles", nomeIngles: "SEYCHELLES"},
    {sigla: "SN", nome:"Senegal", nomeIngles: "SENEGAL"},
    {sigla: "SL", nome:"Serra Leoa", nomeIngles: "SIERRA LEONE"},
    {sigla: "RS", nome:"Servia", nomeIngles: "SERBIA"},
    {sigla: "SG", nome:"Singapura", nomeIngles: "SINGAPORE"},
    {sigla: "SY", nome:"Síria", nomeIngles: "SYRIA"},
    {sigla: "SO", nome:"Somalia", nomeIngles: "SOMALIA"},
    {sigla: "LK", nome:"Sri Lanka", nomeIngles: "SRI LANKA"},
    {sigla: "SZ", nome:"Suazilândia", nomeIngles: "SWAZILAND"},
    {sigla: "SD", nome:"Sudão", nomeIngles: "SUDAN"},
    {sigla: "SS", nome:"Sudão do Sul", nomeIngles: "SOUTH SUDAN"},
    {sigla: "SE", nome:"Suécia", nomeIngles: "SWEDEN"},
    {sigla: "CH", nome:"Suíça", nomeIngles: "SWITZERLAND"},
    {sigla: "SR", nome:"Suriname", nomeIngles: "SURINAME"},
    {sigla: "TJ", nome:"Tadjquistão", nomeIngles: "TAJKISTAN"},
    {sigla: "TH", nome:"Tailândia", nomeIngles: "THAILAND"},
    {sigla: "TW", nome:"Taiwan", nomeIngles: "TAIWAN"},
    {sigla: "TZ", nome:"Tanzânia", nomeIngles: "TANZANIA"},
    {sigla: "TL", nome:"Timor-Leste", nomeIngles: "TIMOR-LESTE"},
    {sigla: "TG", nome:"Togo", nomeIngles: "TOGO"},
    {sigla: "TK", nome:"Tokelau", nomeIngles: "TOKELAU"},
    {sigla: "TO", nome:"Tonga", nomeIngles: "TONGA"},
    {sigla: "TT", nome:"Trindade e Tobago", nomeIngles: "TRINIDAD AND TOBAGO"},
    {sigla: "TN", nome:"Tunísia", nomeIngles: "TUNISIA"},
    {sigla: "TM", nome:"Turcomenistão", nomeIngles: "TURKMENISTAN"},
    {sigla: "TC", nome:"Turks e Caicos", nomeIngles: "TURKS AND CAICOS ISLANDS"},
    {sigla: "TR", nome:"Turquia", nomeIngles: "TURKEY"},
    {sigla: "TV", nome:"Tuvalu", nomeIngles: "TUVALU"},
    {sigla: "UA", nome:"Ucrânia", nomeIngles: "UKRAINE"},
    {sigla: "UG", nome:"Uganda", nomeIngles: "UGANDA"},
    {sigla: "UY", nome:"Uruguai", nomeIngles: "URUGUAY"},
    {sigla: "UZ", nome:"Uzbequistão", nomeIngles: "UZBEKISTAN"},
    {sigla: "VU", nome:"Vanuatu", nomeIngles: "VANUATU"},
    {sigla: "VE", nome:"Venezuela", nomeIngles: "VENEZUELA"},
    {sigla: "VN", nome:"Vietnã", nomeIngles: "VIETNAM"},
    {sigla: "ZM", nome:"Zâmbia", nomeIngles: "ZAMBIA"},   
    {sigla: "ZW", nome:"Zimbábue", nomeIngles: "ZIMBABWE"}
]